name: spalmc
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.1
  - cpuonly
  - anndata>=0.10
  - scanpy>=1.9
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - h5py
  - matplotlib
  - pip
